# Usar la imagen oficial de Python
FROM python:3.11

# Establecer el directorio de trabajo en /app
WORKDIR /app

# Copiar el archivo requirements.txt al contenedor
COPY requirements.txt .

# Instalar las dependencias del proyecto
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto de los archivos al contenedor
COPY . .

# CMD para ejecutar el script Python
CMD ["python", "Entregable Gustavo Martín.ipynb"]
